server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/murdering/SpringCloud.Samples/
          search-paths: src/spring-cloud-config/config-repo
          username:
          password: